### PR TITLE
Made Footer Fixed in Bottom and Fixed Menu

### PR DESCRIPTION
**Pull request by asubodh**
# Changes 
- Made Footer Fixed in Bottom
- Fixed Menu on all the pages.
- Fixed CSS (font) on Contact Us Page.

## Preview
[screen-recorder-mon-oct-31-2022-17-14-31.webm](https://user-images.githubusercontent.com/43497160/198998200-daef8c05-406c-4eb0-a9fb-81196f5b0f78.webm)

### CODE REVIEW

**Review by asdsyd — CHANGES_REQUESTED** [review]
There's lot of file changes unnecessary. Please make a good PR.

**Comment by asubodh** [comment]
# More Changes 
- Added Footer on all Pages.
- Fixed Menu on all the pages.
- Added Automatic Generating Image on the home page.
- Made the FAQ text capitalized.
## Preview
[screen-recorder-mon-oct-31-2022-20-14-51.webm](https://user-images.githubusercontent.com/43497160/199032273-f565d2bf-cd23-48e1-877c-ab5b36eedd50.webm)

**Comment by asubodh** [comment]
@asdsyd Please take a look.

**Review by asdsyd — APPROVED** [review]
Looks good. Thanks for contributing this hacktoberfest!🚀

**Pull request merged**
