### PR TITLE
FAQ page added

### LINKED ISSUE #22: Design FAQ page for healthy-dev
- [ ] Use tailwind css
- [ ] Include a screenshot of render
- [ ] Minimum 5 FAQs included
- [ ] Consistent design language
- [ ] Link PR to this issue using this text --> 'Closes #issueNumber'

### PR DESCRIPTION
**Pull request by jsvigneshkanna**
@asdsyd 

Description:

FAQ page updated with 5 FAQs and styled with tailwind accordion

Closes #22 

Screenshot:
image

### CODE REVIEW

**Review by asdsyd — CHANGES_REQUESTED** [review]
There's another PR to be merged which changes the folder structure. You need to move the html and css into respective folders. 
Thank you.

**Comment by asdsyd** [comment]
After the PR is merged. Good work 👍

**Comment by jsvigneshkanna** [comment]
add a comment once another PR is merged @asdsyd

**Comment by asdsyd** [comment]
@jsvigneshkanna Go ahead update your fork.

**Review by asdsyd — APPROVED** [review]
Looks good. The other PR had some issues. Merging your PR. Thanks for contributing. ❤️

**Pull request merged**
