### PR TITLE
Create explore.html page with 9 new cards

### LINKED ISSUE #6: Home page content design.
Open to suggestions.
You can make 3x3 cards that contain titles like mental health, productivity, sleep, food, coffee etc sections
or 
9 vertical colorful columns with clickable titles? 
Something like this below but bigger cards? using tailwind CSS

Screenshot 2022-10-14 at 9 11 50 PM

### PR DESCRIPTION
**Pull request by ishaanbedi**
'Closes #6'

### CODE REVIEW

**Comment by asdsyd** [comment]
Thanks for contribution. ❤️

**Comment by ishaanbedi** [comment]
It's my pleasure! Great working with you!

**Comment by asdsyd** [comment]
This is not redirecting to explore.html Please check

**Comment by ishaanbedi** [comment]
> This is not redirecting to explore.html Please check

Sure! let me check

**Comment by asdsyd** [comment]
https://user-images.githubusercontent.com/77977076/195921853-c704ba55-7daf-41fe-b33f-b5c7eaf86054.mov

**Comment by ishaanbedi** [comment]
My bad! I missed committing the index.html file. I've raised a pr for the same.

**Comment by asdsyd** [comment]
I have reverted the prev PR. Will merge the latest one. Okay no problem.

**Pull request merged**
