### PR TITLE
design of healthy developer

### LINKED ISSUE #8: Design social media image.
Social preview
Upload an image to customize your repository’s social media preview.

It should include:
- Healthy Developer title
- Any good logo

The best design would be selected.

Note:
Images should be at least 640×320px (1280×640px for best display).

repository-open-graph-template

### PR DESCRIPTION
**Pull request by 72002sweta**
'Closes #8 '

### CODE REVIEW

**Review by asdsyd — CHANGES_REQUESTED** [review]
This is great. Can you do a version with a light purple in it like this mint one. Thanks.

**Comment by asdsyd** [comment]
Do add this line at the end 
Screenshot 2022-10-16 at 10 15 51 PM

**Comment by 72002sweta** [comment]
okaii sure

**Comment by 72002sweta** [comment]
done the changes please review

**Review by asdsyd — APPROVED** [review]
Beautiful. 
Thanks for contributing🚀

**Pull request merged**
